/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9d50a76cdc759facba0bb43994cbf977)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/_worker.js/index");
	}
	interface Env {
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
