/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e5cc075b4b2aa357634eb11e595758d7)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/_worker.js/index");
	}
	interface Env {
		GIT_REPO_NAME: string;
		GIT_REF: string;
		GIT_SHA: string;
		GIT_SHA_SHORT: string;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string
		? EnvType[Binding]
		: string;
};
declare namespace NodeJS {
	interface ProcessEnv
		extends StringifyValues<
			Pick<
				Cloudflare.Env,
				"GIT_REPO_NAME" | "GIT_REF" | "GIT_SHA" | "GIT_SHA_SHORT"
			>
		> {}
}
